# Generated by Django 5.0.6 on 2024-05-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownmenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_items', to='navbar.menuitem'),
        ),
        migrations.AlterField(
            model_name='megamenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mega_items', to='navbar.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='navbar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='navbar.navbar'),
        ),
    ]
